version: "3.9"


services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "${PG_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
  web:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "${GO_PORT}:${GO_PORT}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .env:/app/.env



